### ISSUE TITLE
IDB file not saved after decoder run

### ISSUE THREAD

**Issue by tguilday** [Defense-Cyber-Crime-Center/kordesii#30]
If you use the CLI tool and provide it with a filename **without a file extension**, kordesii **does not save the patched .idb file** after it runs the decoder (it only provides the CLI output to console) i.e. (renamed strings.exe to strings for testing purposes)
```
kordesii parse Sample ./kordesii/decoders/tests/strings
``` 

If you provide kordesii with a filename **with an extension**, kordesii _will_ save and provide the patched .idb file after it runs the decoder:
```
kordesii parse Sample ./kordesii/decoders/tests/strings.exe
```

Is this the intended behavior?

**Comment by DC3-DCCI** [comment]
Originally, by default it is suppose to remove the .idb file. In order to keep the idb file, you must include the `--no-cleanup` flag. However, it looks like at some point Hex-Rays changed the filename schema to no longer remove the extension (ie. for the input file `strings.exe` instead of  `strings.idb` it is now  `strings.exe.idb`). The code in kordesii is still assuming the extensions gets removed and therefore doesn't end up deleting the idb file. Which explains why it does work when there is no extension.

In the most recent release 2.3.0, we've updated the logic to properly cleanup the idb when cleanup is enabled. However, since most users are probably now used to the idb not being cleaned up by default thanks to this bug, the `--no-cleanup` flag has been set as the default. Instead, one must use the `--cleanup` flag to ensure the idb file is removed.

Hopefully this fixes your issue. Thanks for discovering this!
